--- 
javascripts: 
- base:
  - jQuery 
  - ufo
  - jquery.tablednd_0_5
  - jquery.prettyPhoto
  - jquery.parseUri
  - jquery.jcarousel_lite
  - application
stylesheets: 
- base: 
  - base
  - colours
  - common
  - jquery.jcarousel
  - layout
  - prettyPhoto
  - yellow
