development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Bort
  admin_email: bort@bort.com
  
test:
  <<: *non_production_settings

staging:
  <<: *non_production_settings
  
production:
  site_url: http://AnnaCole.co.uk
  site_name: AnnaCole.co.uk
  admin_email: oliver.nightingale2@ntlworld.com
